---
title: "Energy Access Project Overview- Nara"
author: "Nara McCray"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Sections which are my responsibility have my name in parenthesis

**Survey Data Cleaning:** (Nara)
-Clean data, recode, and sepeate into a dataframe for each survey year, aggregate to cluster level by averaging
-Produce summary statistics charts using *ggplot2* package
-Attach survey data to cluster centroids
_Aggregate cluster centroid to districts by averaging
  -All survey years will be added to same districts object

**Raster Analysis:** (Dan)
- Create maps of energy access rates, common sources of energy by region, and deforestation rates (both at base raster resolution and aggregated by region)

**Statistical Analysis of Correlation:** (Dan and Nara)
- Correlate rates of energy access and rates of deforestation using regression modeling with *lm* module
- Other statistical analyses as needed, aggregated over a range of scales

**Beautification of Map and Chart Outputs:** (Nara and Dan)
- Make pretty maps including region outlines
- Possibly focus on some regions with the most vivid results
